# =============================================================================
# @project    ELY — Exactly Like You
# @file       backend/app/models/learned_skill.py
# @brief      Sprint 4b Phase 1 — auto-improved skills (Hermes-style playbooks)
#
# @author     Franck OLLIVIER <contact@agent-ely.fr>
# @copyright  Copyright (c) 2025-2026 Franck OLLIVIER — All rights reserved
# @license    PolyForm Strict License 1.0.0
#             https://polyformproject.org/licenses/strict/1.0.0/
# =============================================================================
"""Learned skills — Sprint 4b Phase 1 (auto-amélioration par création de skills).

A LearnedSkill is the persisted output of the skill_creator loop: a
Markdown playbook (Hermes ``SKILL.md`` format with YAML frontmatter)
that describes "when situation X arises, do Y in this order". It's
injected into the system prompt at runtime when its trigger pattern
matches the current conversation.

Why Markdown rather than Python code (Hermes-style, see design note §1):
  - 90% of ELY failures are procedural / contextual (HITL refused,
    hallucinations, mission critiques) — fixable by a playbook
  - No sandbox needed (the content is injected as text, never executed)
  - HITL admin promotion is auditable (reading a diff of Markdown is
    much easier than reviewing generated Python code)
  - SKILL.md is compatible with the agentskills.io standard, so once
    Sprint 8 lands ELY can both import community skills and export its
    learned ones.

V2 (Sprint 4b — @tool Python génération, design note J0):
  The "never executed" boundary above holds for ``markdown_playbook``
  skills. V2 adds a second ``content_format`` — ``python_tool`` — where
  ``content`` is Python ``@tool`` source that IS compiled and bound to
  the LLM, but only after the validation pipeline (AST allow-list →
  ruff → mypy → smoke sandbox → regression bench) AND HITL admin. V2 is
  deliberately scoped to *composition of existing tools + pure-compute
  stdlib (zero I/O)* — genuine new-I/O extension (new APIs) is V3-behind-
  Docker. See ``SkillContentFormat`` and design note J0 §3.

Pattern d'inspiration : Hermes ``tools/skill_manager_tool.py`` + ``agent/curator.py``
voir docs/external-references/hermes-skills-self-improvement.md
Implémentation : code maison, adapté au modèle multi-tier ELY (tier S dédié
+ HITL promotion + DB storage rather than filesystem).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ── Status enum (as plain strings — see Domain in app/skills/base.py) ──────
class SkillStatus:
    """Lifecycle states for a LearnedSkill.

    ``candidate``  Generated by the skill_creator, eval not yet passed
                   OR pending HITL admin promotion.
    ``active``     In production: injected into the system prompt when
                   its trigger pattern matches.
    ``stale``      Active but not used in the last `stale_after_days`
                   (curator transition, recoverable by usage).
    ``archived``   Hidden from prompt injection; never deleted, recoverable
                   via the admin UI (curator transition).
    ``rejected``   Eval loop exhausted its N iterations without passing;
                   permanent failure record. Not promoted, not curated.
    """

    CANDIDATE = "candidate"
    ACTIVE = "active"
    STALE = "stale"
    ARCHIVED = "archived"
    REJECTED = "rejected"

    ALL = {CANDIDATE, ACTIVE, STALE, ARCHIVED, REJECTED}
    # States visible to the prompt injection layer (active session use).
    PROMPT_VISIBLE = {ACTIVE}


# ── Source enum ─────────────────────────────────────────────────────────────
class SkillSource:
    """Where this LearnedSkill came from.

    The curator only touches ``auto_generated`` skills. ``user_added``
    skills are immune (the user wrote them, the system never archives
    them). ``imported_marketplace`` are skills pulled from agentskills.io
    or the community marketplace (Sprint 8) — also user-controlled.
    """

    AUTO_GENERATED = "auto_generated"
    USER_ADDED = "user_added"
    IMPORTED_MARKETPLACE = "imported_marketplace"

    ALL = {AUTO_GENERATED, USER_ADDED, IMPORTED_MARKETPLACE}
    # Subset the auto-curator is allowed to mutate.
    CURATOR_MUTABLE = {AUTO_GENERATED}


# ── Content format enum (V2, Sprint 4b) ─────────────────────────────────────
class SkillContentFormat:
    """How ``LearnedSkill.content`` is interpreted.

    ``markdown_playbook``  V1 — content is a Markdown SKILL.md body,
                           injected into the system prompt as text and
                           **never executed**. The original, default
                           format; every pre-V2 row is this.
    ``python_tool``        V2 — content is Python ``@tool`` source code
                           (a composition of already-registered ELY
                           tools + pure-computation stdlib, **zero
                           I/O**). Compiled and bound to the LLM only
                           after the validation pipeline (AST allow-list
                           → ruff → mypy → smoke sandbox → regression
                           bench) AND HITL admin promotion.

    ``python_tool`` is exactly the frontier the LearnedSkill V1 docstring
    called "never executed". V2 crosses it on purpose — design note J0 §3
    carries the threat model that makes the non-sandboxed runtime
    defensible (composition-only + AST allow-list + HITL).
    """

    MARKDOWN_PLAYBOOK = "markdown_playbook"
    PYTHON_TOOL = "python_tool"

    ALL = {MARKDOWN_PLAYBOOK, PYTHON_TOOL}


class LearnedSkill(Base):
    """One Markdown playbook + metadata, user-scoped."""

    __tablename__ = "learned_skills"

    id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    user_id: Mapped[str] = mapped_column(String, ForeignKey("users.id"), index=True)

    # SKILL.md frontmatter mirrors (extracted for indexing / querying)
    name: Mapped[str] = mapped_column(String(64), index=True)  # slug
    description: Mapped[str] = mapped_column(String(1024))     # one-liner shown to the agent

    # Full Markdown body (without frontmatter — frontmatter is rebuilt
    # from the indexed columns when serialising for the agent prompt).
    content: Mapped[str] = mapped_column(Text)

    # Extra frontmatter fields (tags, related_skills, prerequisites,
    # platforms…) stored as JSON for forward compatibility with
    # agentskills.io evolutions. Empty dict {} at minimum.
    frontmatter_json: Mapped[str] = mapped_column(Text, default="{}")

    # V2 (Sprint 4b) — how `content` is interpreted: markdown_playbook
    # (V1, injected as text, never executed) vs python_tool (V2, compiled
    # + bound after the validation pipeline + HITL). Default keeps every
    # existing row a playbook. See SkillContentFormat + design note J0.
    content_format: Mapped[str] = mapped_column(
        String(20),
        default=SkillContentFormat.MARKDOWN_PLAYBOOK,
    )
    # V2 — JSON report of the 5-stage validation pipeline (ast / ruff /
    # mypy / smoke / bench), one entry per stage. "{}" for markdown
    # playbooks and for python_tool skills not yet validated.
    validation_report_json: Mapped[str] = mapped_column(Text, default="{}")

    # Lifecycle + provenance (see enums above).
    status: Mapped[str] = mapped_column(
        String(16),
        default=SkillStatus.CANDIDATE,
        index=True,
    )
    source: Mapped[str] = mapped_column(
        String(32),
        default=SkillSource.AUTO_GENERATED,
        index=True,
    )

    # Skill_creator bookkeeping
    iteration_count: Mapped[int] = mapped_column(Integer, default=0)
    # 0-100 from the LLM-as-judge on the replay. NULL = not yet evaluated.
    last_eval_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # JSON list of failure_case ids this skill was generated to address.
    from_failure_case_ids: Mapped[str] = mapped_column(Text, default="[]")
    # Why the agent created this skill (free text, ~500 chars).
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)

    # User overrides the curator: pinned skills never auto-transition to
    # stale/archived even when unused for months.
    pinned: Mapped[bool] = mapped_column(Boolean, default=False)

    # Last time the agent loaded this skill into a prompt (for curator
    # stale detection). NULL until first use.
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    # Cumulative usage counter (cheap analytics for the UI).
    use_count: Mapped[int] = mapped_column(Integer, default=0)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, index=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=_utcnow,
        onupdate=_utcnow,
    )
