# =============================================================================
# @project    ELY — Exactly Like You
# @file       backend/app/routers/licence.py
# @brief      Licence status endpoint — Elastic License v2 (info-only)
#
# @author     Franck OLLIVIER <contact@agent-ely.fr>
# @copyright  Copyright (c) 2025-2026 Franck OLLIVIER — All rights reserved
# @license    Elastic License 2.0
#             https://www.elastic.co/licensing/elastic-license
# =============================================================================
"""Licence routes — info-only after the 22 May 2026 pivot.

Pre-2026-05-28 this router exposed:
  * GET  /api/licence/status         (auth required)
  * POST /api/licence/activate-free  (admin, click-wrap)
  * POST /api/licence/activate-paid  (admin, paste key + tier)

After the Elastic License v2 pivot there is no activation flow and no
tiers, so the POST endpoints have been removed. Only the GET remains,
returning a static payload generated by ``get_licence_status``.
"""
from __future__ import annotations

import logging

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import get_current_user
from app.database import get_db
from app.models.user import User
from app.services.licence_service import get_licence_status

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/licence", tags=["licence"])


@router.get("/status")
async def licence_status(
    _user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Return the current licence information.

    Any authenticated user can read this — the frontend Settings panel
    uses it to render the read-only "Elastic License v2" summary card.
    """
    return await get_licence_status(db)
