# =============================================================================
# @project    ELY — Exactly Like You
# @file       backend/app/services/learning/code_guard.py
# @brief      Sprint 4b V2 J2 — AST allow-list guard for generated @tool code.
#
# @author     Franck OLLIVIER <contact@agent-ely.fr>
# @copyright  Copyright (c) 2025-2026 Franck OLLIVIER — All rights reserved
# @license    Elastic License 2.0
#            https://www.elastic.co/licensing/elastic-license
# =============================================================================
"""Stage 1 of the V2 validation pipeline — static AST allow-list.

This is the load-bearing safety gate (design note J0 §3.3). A V2
``python_tool`` skill is generated by a tier-S LLM and, once promoted,
its source is compiled and bound to the LLM and runs **in the backend
process** (not sandboxed at runtime — see J0 §3.1). So before any
execution, this guard parses the source and rejects anything outside a
deliberately tiny allow-list:

  - imports limited to pure-compute stdlib (zero I/O) + the @tool/@register
    scaffolding ELY tools need;
  - no dangerous builtins (eval/exec/compile/open/__import__/getattr/…);
  - no dunder attribute/name access (the classic
    ``().__class__.__bases__[0].__subclasses__()`` sandbox-escape family);
  - no ``global`` / ``nonlocal`` / ``import *`` / relative imports.

Everything the guard forbids (``os``, ``socket``, ``open``, ``subprocess``,
``urllib`` …) is precisely the surface V3 will open behind a Docker
sandbox. V2 is scoped to *composition of existing tools + pure-compute
stdlib* — see ``SkillContentFormat`` in app/models/learned_skill.py.

The guard is intentionally **deny-by-default** and conservative: a false
positive (rejecting safe code) only costs the generator another
iteration; a false negative (letting an escape through) runs arbitrary
code in-process. When in doubt, forbid.

This module is pure — no DB, no I/O, no LLM. Trivially unit-testable,
which is the point: the test suite enumerates the bypass vectors.
"""
from __future__ import annotations

import ast
from dataclasses import dataclass, field
from typing import Literal


# ── Allow-lists ──────────────────────────────────────────────────────────────
# A module M is allowed if  M.split(".")[0] in ALLOWED_IMPORT_ROOTS
#                       OR  M in ALLOWED_IMPORT_EXACT.
# Roots cover stdlib families (so `collections.abc` rides on `collections`);
# EXACT pins the scaffolding modules so we DON'T open all of `app.*`.

ALLOWED_IMPORT_ROOTS: frozenset[str] = frozenset({
    # pure-compute stdlib — no network, no filesystem, no process
    "math",
    "json",
    "re",
    "datetime",
    "statistics",
    "itertools",
    "collections",
    "decimal",
    "fractions",
    "functools",
    "string",
    "textwrap",
    "typing",
    "dataclasses",
    "enum",
    "__future__",
})

ALLOWED_IMPORT_EXACT: frozenset[str] = frozenset({
    # the @tool / @register scaffolding (see docs/ADDING_A_TOOL.md)
    "langchain_core.tools",
    "app.skills.decorator",
    "app.skills.base",
    # Sprint 4b V2 composition (N1): the bridge a generated tool uses to call
    # other ELY tools. `call_tool` itself refuses critical/HITL tools, so this
    # import grants only the SAFE composition surface — defence in depth.
    "app.services.learning.learned_tool_dispatch",
})


# ── Sprint 4b V3 J3 — "io" profile ───────────────────────────────────────────
# V3 tools may do real network I/O. They run inside the sandbox container
# (read-only rootfs, dropped caps, no native Internet route — outbound is
# clamped through the egress-proxy allow-list). So the threat model at the
# AST level shifts: we don't need to prevent the *act* of making an HTTP
# call (the proxy + network isolation does that), we need to prevent the
# *escape patterns* (eval/exec/__import__/dunder-attr access) that would
# let a malicious tool bypass our chain.
#
# V3.0 SCOPE — HTTP GET read-only:
#   - httpx        — modern HTTP client (sync + async)
#   - beautifulsoup4 (top-level package name `bs4`) — HTML/XML parsing
#   - lxml         — fast XML/HTML parser, used by bs4 internals
#
# The same curated set is BAKED INTO the sandbox image (sandbox/Dockerfile)
# so the import being "allowed" and the import "actually resolving" stay in
# lockstep. Bumping either side is a PR; both sides must move together.
#
# FORBIDDEN_CALLS is UNCHANGED — even an "io" tool can't `eval(...)` or
# `__import__("os").system(...)`. The escape patterns are the real risk;
# the libraries themselves do nothing the proxy can't gate.
ALLOWED_IMPORT_ROOTS_IO: frozenset[str] = ALLOWED_IMPORT_ROOTS | frozenset({
    "httpx",
    "bs4",
    "lxml",
})

ALLOWED_IMPORT_EXACT_IO: frozenset[str] = ALLOWED_IMPORT_EXACT


# ── Profile dispatch ─────────────────────────────────────────────────────────
# Stays a dict (not just an if/elif) so adding a future "io_post" or
# "io_extended" profile is one entry plus its own frozensets, no plumbing.
GuardProfile = Literal["pure", "io"]

_PROFILE_SETS: dict[str, tuple[frozenset[str], frozenset[str]]] = {
    "pure": (ALLOWED_IMPORT_ROOTS, ALLOWED_IMPORT_EXACT),
    "io":   (ALLOWED_IMPORT_ROOTS_IO, ALLOWED_IMPORT_EXACT_IO),
}

# Builtins that are escape hatches or perform I/O. Flagged when called as a
# bare name: `eval(...)`, `open(...)`. Note `re.compile(...)` is an Attribute
# call (re.compile), NOT a bare-name Call, so it is correctly NOT flagged —
# only the builtin `compile(...)` is.
FORBIDDEN_CALLS: frozenset[str] = frozenset({
    "eval",
    "exec",
    "compile",
    "__import__",
    "open",
    "input",
    "globals",
    "locals",
    "vars",
    "getattr",
    "setattr",
    "delattr",
    "hasattr",
    "memoryview",
    "breakpoint",
    "help",
    "exit",
    "quit",
})


# ── Result types ─────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Violation:
    """One rule break. ``code`` is a stable machine key; ``detail`` is
    human-readable; ``lineno``/``col`` locate it in the source."""

    code: str
    detail: str
    lineno: int
    col: int

    def __str__(self) -> str:  # pragma: no cover - cosmetic
        return f"[{self.code}] line {self.lineno}: {self.detail}"


@dataclass(frozen=True)
class GuardReport:
    """Outcome of :func:`check_tool_source`. ``ok`` is True iff there are
    zero violations."""

    ok: bool
    violations: tuple[Violation, ...] = field(default_factory=tuple)

    def summary(self) -> str:
        if self.ok:
            return "ok"
        return "; ".join(str(v) for v in self.violations)


# ── Helpers ──────────────────────────────────────────────────────────────────


def _is_dunder(identifier: str) -> bool:
    """True for the escape-vector identifiers — anything starting with a
    double underscore (``__class__``, ``__globals__``, ``__builtins__``,
    ``__subclasses__``, ``__import__`` …). Single-underscore names are
    fine. ``__future__`` only ever appears as an import module (a string
    on ImportFrom, never a Name/Attribute node), so it is never matched
    here."""
    return identifier.startswith("__")


def _module_allowed(module: str | None) -> bool:
    if not module:
        return False
    if module in ALLOWED_IMPORT_EXACT:
        return True
    root = module.split(".", 1)[0]
    return root in ALLOWED_IMPORT_ROOTS


# ── The guard ────────────────────────────────────────────────────────────────


def check_tool_source(
    source: str,
    *,
    profile: GuardProfile = "pure",
    allowed_import_roots: frozenset[str] | None = None,
    allowed_import_exact: frozenset[str] | None = None,
) -> GuardReport:
    """Statically validate generated ``@tool`` source. Returns a
    :class:`GuardReport` collecting **all** violations (not just the
    first), so the generator gets full feedback in one pass.

    ``profile``:
        - ``"pure"`` (default) — V2 N1/N2 scope: stdlib pure-compute + the
          scaffolding + ``call_tool`` for safe composition. NO network, NO
          I/O. Backward-compatible with every existing call-site.
        - ``"io"`` — V3 scope: V2 allow-list PLUS the curated network/parse
          libs (httpx / bs4 / lxml) baked into the sandbox image. Used by
          tools that actually do HTTP GET-style network reads. The escape
          ban (``FORBIDDEN_CALLS``) is identical — the relaxation is import
          allow-list only.

    ``allowed_import_roots`` / ``allowed_import_exact`` are an explicit
    escape hatch (tests, future tuning). When set, they take precedence over
    the profile-resolved defaults.
    """
    if profile not in _PROFILE_SETS:
        raise ValueError(
            f"unknown guard profile {profile!r} — valid: {sorted(_PROFILE_SETS)}"
        )
    default_roots, default_exact = _PROFILE_SETS[profile]
    roots = allowed_import_roots if allowed_import_roots is not None else default_roots
    exact = allowed_import_exact if allowed_import_exact is not None else default_exact

    def _mod_ok(module: str | None) -> bool:
        if not module:
            return False
        if module in exact:
            return True
        return module.split(".", 1)[0] in roots

    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return GuardReport(
            ok=False,
            violations=(
                Violation(
                    code="syntax_error",
                    detail=f"source does not parse: {exc.msg}",
                    lineno=exc.lineno or 0,
                    col=exc.offset or 0,
                ),
            ),
        )

    violations: list[Violation] = []

    def _add(code: str, detail: str, node: ast.AST) -> None:
        violations.append(
            Violation(
                code=code,
                detail=detail,
                lineno=getattr(node, "lineno", 0),
                col=getattr(node, "col_offset", 0),
            )
        )

    for node in ast.walk(tree):
        # ── imports ──────────────────────────────────────────────────
        if isinstance(node, ast.Import):
            for alias in node.names:
                if not _mod_ok(alias.name):
                    _add(
                        "forbidden_import",
                        f"import of '{alias.name}' is not in the V2 allow-list",
                        node,
                    )
        elif isinstance(node, ast.ImportFrom):
            if node.level and node.level > 0:
                _add(
                    "forbidden_import",
                    "relative imports are not allowed",
                    node,
                )
                continue
            if any(a.name == "*" for a in node.names):
                _add(
                    "forbidden_import",
                    f"'from {node.module} import *' is not allowed (star import)",
                    node,
                )
                continue
            if not _mod_ok(node.module):
                _add(
                    "forbidden_import",
                    f"import from '{node.module}' is not in the V2 allow-list",
                    node,
                )

        # ── global / nonlocal — mutating outer scope ─────────────────
        elif isinstance(node, ast.Global):
            _add("forbidden_statement", "'global' is not allowed", node)
        elif isinstance(node, ast.Nonlocal):
            _add("forbidden_statement", "'nonlocal' is not allowed", node)

        # ── dangerous builtin calls (bare-name only) ─────────────────
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in FORBIDDEN_CALLS:
                _add(
                    "forbidden_call",
                    f"call to '{node.func.id}' is not allowed",
                    node,
                )

        # ── dunder attribute access:  x.__class__ , obj.__globals__ ──
        elif isinstance(node, ast.Attribute):
            if _is_dunder(node.attr):
                _add(
                    "dunder_access",
                    f"access to dunder attribute '.{node.attr}' is not allowed",
                    node,
                )

        # ── dunder name reference:  __builtins__ , __import__ ────────
        elif isinstance(node, ast.Name):
            if _is_dunder(node.id):
                _add(
                    "dunder_access",
                    f"reference to dunder name '{node.id}' is not allowed",
                    node,
                )

    return GuardReport(ok=not violations, violations=tuple(violations))


def is_safe(source: str, *, profile: GuardProfile = "pure") -> bool:
    """Convenience boolean wrapper around :func:`check_tool_source`."""
    return check_tool_source(source, profile=profile).ok
