'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {autonomy,type Check} from '@/lib/autonomy';
import {CriteriaEditor} from './criteria';
type Preferences=Record<string,string>;
type Procedure={id:string;name:string;description:string;status:string;pinned:boolean;counts:Record<string,number>;suspension:string|null};
type Follow={id:string;title:string;status:string;question:string|null;waiting_for:string|null;checks:Check[];results:({kind:string;passed:boolean;evidence:string[]})[];provider_retries:number};
type Receipt={id:string;tool_name:string;status:string;result:string};
const categories=[['read','Consulter et rechercher'],['write','Créer ou modifier des contenus privés'],['engage','Actions engageantes (envoi, suppression, publication…)'],['system','Accéder aux fichiers avec Ely Desktop'],['unknown','Outils dont l’effet n’est pas encore classé']];
const states:Record<string,string>={planning:'Préparation',running:'En cours',waiting_user:'Décision attendue',paused:'En pause',completed:'Terminée',failed:'Échec',aborted:'Arrêtée',draft:'Brouillon'};
export function AutonomyControl({section}:{section:string}) {
  const [prefs,setPrefs]=useState<Preferences|null>(null),[procedures,setProcedures]=useState<Procedure[]>([]),[missions,setMissions]=useState<Follow[]>([]);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{if(section==='permissions')setPrefs(await autonomy<Preferences>('/preferences'));else if(section==='procedures')setProcedures(await autonomy<Procedure[]>('/procedures'));else setMissions(await autonomy<Follow[]>('/follow'));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}},[section]);
  useEffect(()=>{setLoading(true);setNotice('');setError('');void load();if(section!=='follow')return;const t=setInterval(load,15000);return()=>clearInterval(t);},[load,section]);
  async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await fn();setNotice('Enregistré.');await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <div className="space-y-4">{error&&<p role="alert" className="text-red-300">{error}</p>}{notice&&<p role="status" className="text-cyber-cyan">{notice}</p>}{loading&&<p role="status">Chargement…</p>}
    {section==='permissions'&&prefs&&<form className="card p-4 space-y-4" onSubmit={e=>{e.preventDefault();void run(()=>autonomy('/preferences','PUT',prefs));}}><h2 className="font-medium">Mes limites</h2><p className="text-sm text-text-muted">Ces choix s’appliquent au chat, aux missions et aux tâches planifiées. Les accès aux comptes et aux dossiers restent ceux de Paramètres → Intégrations.</p>{categories.map(([key,label])=><label key={key} className="flex flex-wrap justify-between items-center gap-3"><span>{label}</span><select className="bg-bg-secondary border border-border-dim p-2 rounded" value={prefs[key]} onChange={e=>setPrefs({...prefs,[key]:e.target.value})}><option value="inherit">Selon mes autorisations existantes</option><option value="confirm">Toujours me demander</option><option value="deny">Interdire</option></select></label>)}<label className="flex flex-wrap justify-between items-center gap-3"><span>Notifications de mission</span><select className="bg-bg-secondary border border-border-dim p-2 rounded" value={prefs.notifications} onChange={e=>setPrefs({...prefs,notifications:e.target.value})}><option value="important">Échecs et blocages utiles</option><option value="all">Aussi les missions terminées</option><option value="none">Suivi dans cette page uniquement</option></select></label><button className="btn primary" disabled={busy}>Enregistrer mes limites</button></form>}
    {section==='procedures'&&<><p className="text-sm text-text-muted">Résultats des outils lors des tours où une procédure a effectivement servi. Ils ne garantissent pas à eux seuls la réussite de toute la demande. Après trois échecs consécutifs, une procédure non épinglée est suspendue.</p>{!loading&&procedures.length===0&&<p>Aucune procédure active ou suspendue.</p>}{procedures.map(p=><article className="card p-4 space-y-2" key={p.id}><h2 className="font-medium">{p.name} · {p.status==='active'?'Active':'Suspendue'}</h2><p className="text-sm">{p.description}</p><p className="text-sm text-text-muted">{p.counts.success||0} exécutions sans erreur observée · {p.counts.failed||0} échecs · {p.counts.pending||0} non vérifiées{p.pinned?' · Épinglée (suspension manuelle)':''}</p>{p.suspension&&<p className="text-amber-300">{p.suspension}</p>}<button className="btn" disabled={busy} onClick={()=>void run(()=>autonomy(`/procedures/${p.id}/enabled`,'PUT',{enabled:p.status!=='active'}))}>{p.status==='active'?'Suspendre':'Réactiver'}</button></article>)}</>}
    {section==='follow'&&<><div className="grid grid-cols-3 gap-3">{[['En cours',missions.filter(m=>['planning','running'].includes(m.status)).length],['En attente',missions.filter(m=>m.status==='paused').length],['À décider',missions.filter(m=>m.status==='waiting_user').length]].map(([label,n])=><div key={label} className="card p-3"><strong className="text-xl text-cyber-cyan">{n}</strong><p className="text-xs">{label}</p></div>)}</div>{!loading&&missions.length===0&&<p>Aucune mission pour le moment. <Link className="text-cyber-cyan underline" href="/missions">Créer une mission</Link></p>}{missions.map(m=><MissionFollow key={m.id} m={m}/>)}</>}
  </div>;
}
function MissionFollow({m}:{m:Follow}) {
  const [open,setOpen]=useState(false),[checks,setChecks]=useState(m.checks),[receipts,setReceipts]=useState<Receipt[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
  async function load(){setReceipts(await autonomy<Receipt[]>(`/missions/${m.id}/receipts`));}
  async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <article className="card p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><Link className="font-medium text-cyber-cyan underline" href={`/missions/${m.id}`}>{m.title}</Link><span>{states[m.status]||m.status}</span></div>{m.question&&<p className="text-amber-200 text-sm">{m.question}</p>}{m.provider_retries>0&&<p className="text-xs">Fournisseur temporairement indisponible · reprise {m.provider_retries}/5</p>}{m.results.map((r,i)=><p className="text-sm" key={i}>{r.passed?'✓':'À vérifier'} · {r.kind==='tool_success'?'Action attendue':r.kind==='source_count'?'Sources citées':r.kind==='uncertain_action'?'Exécution incertaine':'Texte attendu'} · {r.evidence.length} élément(s) de preuve</p>)}<button className="btn" disabled={busy} onClick={()=>{setOpen(!open);if(!open)void act(async()=>{});}}>{open?'Réduire':'Critères et preuves'}</button>{error&&<p role="alert" className="text-red-300">{error}</p>}{open&&<div className="space-y-4">{['draft','paused','waiting_user'].includes(m.status)?<><CriteriaEditor value={checks} onChange={setChecks}/><button className="btn primary" disabled={busy} onClick={()=>void act(()=>autonomy(`/missions/${m.id}/checks`,'PUT',{checks}))}>Enregistrer les critères</button></>:<p className="text-xs text-text-muted">{m.checks.length} critère(s). Mets la mission en pause pour les modifier.</p>}{receipts.length===0&&<p className="text-sm">Aucune preuve d’exécution enregistrée depuis cette mise à jour.</p>}{receipts.map(r=><div key={r.id} className="border border-border-dim rounded p-3 space-y-2"><p className="text-sm font-medium">{r.tool_name} · {r.status==='success'?'Confirmé par l’outil':r.status==='human_confirmed'?'Confirmé par toi':r.status==='retry_allowed'?'Nouvel essai autorisé':r.status==='failed'?'Échec':'À vérifier'}</p><pre className="whitespace-pre-wrap break-words text-xs max-h-48 overflow-y-auto">{r.result}</pre>{['started','uncertain'].includes(r.status)&&['paused','waiting_user'].includes(m.status)&&<><label className="block text-sm">Ce que tu as vérifié<input className="block w-full bg-bg-secondary border border-border-dim rounded p-2 mt-1" minLength={5} maxLength={1000} value={notes[r.id]||''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/></label><div className="flex flex-wrap gap-2"><button className="btn" disabled={busy||(notes[r.id]||'').trim().length<5} onClick={()=>void act(()=>autonomy(`/receipts/${r.id}/resolve`,'POST',{decision:'done',note:notes[r.id]}))}>L’action a bien eu lieu</button><button className="btn" disabled={busy||(notes[r.id]||'').trim().length<5} onClick={()=>void act(()=>autonomy(`/receipts/${r.id}/resolve`,'POST',{decision:'retry',note:notes[r.id]}))}>Elle n’a pas eu lieu : autoriser un essai</button></div><p className="text-xs text-text-muted">Reprends ensuite la mission depuis sa page. Une confirmation humaine reste distincte d’un accusé d’outil.</p></>}</div>)}</div>}</article>;
}
